//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.20 at 09:49:33 AM KRAT 
//


package com.artmark.avs5router.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.artmark.avs5router.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.artmark.avs5router.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AbstractResponse }
     * 
     */
    public AbstractResponse createAbstractResponse() {
        return new AbstractResponse();
    }

    /**
     * Create an instance of {@link TransitBookResponse }
     * 
     */
    public TransitBookResponse createTransitBookResponse() {
        return new TransitBookResponse();
    }

    /**
     * Create an instance of {@link SetStationInfoRequest }
     * 
     */
    public SetStationInfoRequest createSetStationInfoRequest() {
        return new SetStationInfoRequest();
    }

    /**
     * Create an instance of {@link AbstractResponse.Error }
     * 
     */
    public AbstractResponse.Error createAbstractResponseError() {
        return new AbstractResponse.Error();
    }

    /**
     * Create an instance of {@link TransitBookResponse.Body }
     * 
     */
    public TransitBookResponse.Body createTransitBookResponseBody() {
        return new TransitBookResponse.Body();
    }

    /**
     * Create an instance of {@link TransitConfirmResponse }
     * 
     */
    public TransitConfirmResponse createTransitConfirmResponse() {
        return new TransitConfirmResponse();
    }

    /**
     * Create an instance of {@link SetStationInfoResponse }
     * 
     */
    public SetStationInfoResponse createSetStationInfoResponse() {
        return new SetStationInfoResponse();
    }

    /**
     * Create an instance of {@link TransitCancelRequest }
     * 
     */
    public TransitCancelRequest createTransitCancelRequest() {
        return new TransitCancelRequest();
    }

    /**
     * Create an instance of {@link RouteKey }
     * 
     */
    public RouteKey createRouteKey() {
        return new RouteKey();
    }

    /**
     * Create an instance of {@link Agent }
     * 
     */
    public Agent createAgent() {
        return new Agent();
    }

    /**
     * Create an instance of {@link TransitConfirmRequest }
     * 
     */
    public TransitConfirmRequest createTransitConfirmRequest() {
        return new TransitConfirmRequest();
    }

    /**
     * Create an instance of {@link TransitBookRequest }
     * 
     */
    public TransitBookRequest createTransitBookRequest() {
        return new TransitBookRequest();
    }

    /**
     * Create an instance of {@link TransitCancelResponse }
     * 
     */
    public TransitCancelResponse createTransitCancelResponse() {
        return new TransitCancelResponse();
    }

    /**
     * Create an instance of {@link TransitTicket }
     * 
     */
    public TransitTicket createTransitTicket() {
        return new TransitTicket();
    }

}
