//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.10 at 02:18:32 PM KRAT 
//


package com.artmark.avs5router.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TripType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TripType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="INTERNATIONAL"/>
 *     &lt;enumeration value="INTERREGIONAL"/>
 *     &lt;enumeration value="ADJACENT_INTERREGIONAL"/>
 *     &lt;enumeration value="INTERMUNICIPAL"/>
 *     &lt;enumeration value="MUNICIPAL"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TripType")
@XmlEnum
public enum TripType {

    INTERNATIONAL,
    INTERREGIONAL,
    ADJACENT_INTERREGIONAL,
    INTERMUNICIPAL,
    MUNICIPAL;

    public String value() {
        return name();
    }

    public static TripType fromValue(String v) {
        return valueOf(v);
    }

}
